==38948== Helgrind, a thread error detector
==38948== Copyright (C) 2007-2017, and GNU GPL'd, by OpenWorks LLP et al.
==38948== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==38948== Command: ./bin/kernel PRUEBA_FS 8 ./configs/fibo.config
==38948== Parent PID: 27229
==38948== 
==38948== ---Thread-Announcement------------------------------------------
==38948== 
==38948== Thread #2 was created
==38948==    at 0x49A39F3: clone (clone.S:76)
==38948==    by 0x49A48EE: __clone_internal (clone-internal.c:83)
==38948==    by 0x49126D8: create_thread (pthread_create.c:295)
==38948==    by 0x49131FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==38948==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x10D58A: hilos_kernel (cliente.c:192)
==38948==    by 0x10CBCA: main (main.c:28)
==38948== 
==38948== ---Thread-Announcement------------------------------------------
==38948== 
==38948== Thread #1 is the program's root thread
==38948== 
==38948== ----------------------------------------------------------------
==38948== 
==38948== Possible data race during read of size 1 at 0x4AAAC18 by thread #2
==38948== Locks held: none
==38948==    at 0x4855B06: strlen (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4958863: __tzstring (tzset.c:121)
==38948==    by 0x495AAB1: __tzfile_compute (tzfile.c:606)
==38948==    by 0x49595CE: __tz_convert (tzset.c:580)
==38948==    by 0x487694F: temporal_get_string_time (in /usr/lib/libcommons.so)
==38948==    by 0x48774A1: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x114655: crear_conexion (sockets.c:163)
==38948==    by 0x10CF08: cliente_Memoria_Kernel (cliente.c:25)
==38948==    by 0x10D426: funcion_hilo_cliente_memoria (cliente.c:148)
==38948==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4912AC2: start_thread (pthread_create.c:442)
==38948==  Address 0x4aaac18 is 8 bytes inside a block of size 17 alloc'd
==38948==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4959AC2: __tzfile_read (tzfile.c:275)
==38948==    by 0x4958C23: tzset_internal (tzset.c:405)
==38948==    by 0x49595A6: __tz_convert (tzset.c:577)
==38948==    by 0x487694F: temporal_get_string_time (in /usr/lib/libcommons.so)
==38948==    by 0x48774A1: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x10D60C: hilos_kernel (cliente.c:202)
==38948==    by 0x10CBCA: main (main.c:28)
==38948==  Block was alloc'd by thread #1
==38948== 
==38948== ----------------------------------------------------------------
==38948== 
==38948== Possible data race during read of size 1 at 0x4AAAC19 by thread #2
==38948== Locks held: none
==38948==    at 0x4855B14: strlen (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4958863: __tzstring (tzset.c:121)
==38948==    by 0x495AAB1: __tzfile_compute (tzfile.c:606)
==38948==    by 0x49595CE: __tz_convert (tzset.c:580)
==38948==    by 0x487694F: temporal_get_string_time (in /usr/lib/libcommons.so)
==38948==    by 0x48774A1: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x114655: crear_conexion (sockets.c:163)
==38948==    by 0x10CF08: cliente_Memoria_Kernel (cliente.c:25)
==38948==    by 0x10D426: funcion_hilo_cliente_memoria (cliente.c:148)
==38948==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4912AC2: start_thread (pthread_create.c:442)
==38948==  Address 0x4aaac19 is 9 bytes inside a block of size 17 alloc'd
==38948==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4959AC2: __tzfile_read (tzfile.c:275)
==38948==    by 0x4958C23: tzset_internal (tzset.c:405)
==38948==    by 0x49595A6: __tz_convert (tzset.c:577)
==38948==    by 0x487694F: temporal_get_string_time (in /usr/lib/libcommons.so)
==38948==    by 0x48774A1: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x10D60C: hilos_kernel (cliente.c:202)
==38948==    by 0x10CBCA: main (main.c:28)
==38948==  Block was alloc'd by thread #1
==38948== 
==38948== ----------------------------------------------------------------
==38948== 
==38948== Possible data race during read of size 1 at 0x4AAADA0 by thread #2
==38948== Locks held: none
==38948==    at 0x485881D: bcmp (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x49588A8: __tzstring_len (tzset.c:93)
==38948==    by 0x49588A8: __tzstring (tzset.c:121)
==38948==    by 0x495AAB1: __tzfile_compute (tzfile.c:606)
==38948==    by 0x49595CE: __tz_convert (tzset.c:580)
==38948==    by 0x487694F: temporal_get_string_time (in /usr/lib/libcommons.so)
==38948==    by 0x48774A1: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x114655: crear_conexion (sockets.c:163)
==38948==    by 0x10CF08: cliente_Memoria_Kernel (cliente.c:25)
==38948==    by 0x10D426: funcion_hilo_cliente_memoria (cliente.c:148)
==38948==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4912AC2: start_thread (pthread_create.c:442)
==38948==  Address 0x4aaada0 is 16 bytes inside a block of size 20 alloc'd
==38948==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4958917: __tzstring_len (tzset.c:98)
==38948==    by 0x4958917: __tzstring (tzset.c:121)
==38948==    by 0x495A264: __tzfile_read (tzfile.c:408)
==38948==    by 0x4958C23: tzset_internal (tzset.c:405)
==38948==    by 0x49595A6: __tz_convert (tzset.c:577)
==38948==    by 0x487694F: temporal_get_string_time (in /usr/lib/libcommons.so)
==38948==    by 0x48774A1: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x10D60C: hilos_kernel (cliente.c:202)
==38948==    by 0x10CBCA: main (main.c:28)
==38948==  Block was alloc'd by thread #1
==38948== 
==38948== ----------------------------------------------------------------
==38948== 
==38948== Possible data race during read of size 1 at 0x4AAADA3 by thread #2
==38948== Locks held: none
==38948==    at 0x4856640: strcmp (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x495A8F4: __tzfile_compute (tzfile.c:748)
==38948==    by 0x49595CE: __tz_convert (tzset.c:580)
==38948==    by 0x487694F: temporal_get_string_time (in /usr/lib/libcommons.so)
==38948==    by 0x48774A1: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x114655: crear_conexion (sockets.c:163)
==38948==    by 0x10CF08: cliente_Memoria_Kernel (cliente.c:25)
==38948==    by 0x10D426: funcion_hilo_cliente_memoria (cliente.c:148)
==38948==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4912AC2: start_thread (pthread_create.c:442)
==38948==    by 0x49A3A03: clone (clone.S:100)
==38948==  Address 0x4aaada3 is 19 bytes inside a block of size 20 alloc'd
==38948==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4958917: __tzstring_len (tzset.c:98)
==38948==    by 0x4958917: __tzstring (tzset.c:121)
==38948==    by 0x495A264: __tzfile_read (tzfile.c:408)
==38948==    by 0x4958C23: tzset_internal (tzset.c:405)
==38948==    by 0x49595A6: __tz_convert (tzset.c:577)
==38948==    by 0x487694F: temporal_get_string_time (in /usr/lib/libcommons.so)
==38948==    by 0x48774A1: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x10D60C: hilos_kernel (cliente.c:202)
==38948==    by 0x10CBCA: main (main.c:28)
==38948==  Block was alloc'd by thread #1
==38948== 
==38948== ----------------------------------------------------------------
==38948== 
==38948==  Lock at 0x11A380 was first observed
==38948==    at 0x4854BFE: pthread_mutex_init (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x10AE52: inicializar_mutex (funcionesAuxiliares.c:87)
==38948==    by 0x10CBB1: main (main.c:26)
==38948==  Address 0x11a380 is 0 bytes inside data symbol "mutex_log"
==38948== 
==38948== Possible data race during write of size 1 at 0x4AAC2A3 by thread #1
==38948== Locks held: 1, at address 0x11A380
==38948==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38948==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38948==    by 0x48FDA9C: fputs (iofputs.c:38)
==38948==    by 0x48767C6: txt_write_in_file (in /usr/lib/libcommons.so)
==38948==    by 0x4877522: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x10D60C: hilos_kernel (cliente.c:202)
==38948==    by 0x10CBCA: main (main.c:28)
==38948==  Address 0x4aac2a3 is 83 bytes inside a block of size 4,096 alloc'd
==38948==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==38948==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==38948==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==38948==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==38948==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38948==    by 0x48FDA9C: fputs (iofputs.c:38)
==38948==    by 0x48767C6: txt_write_in_file (in /usr/lib/libcommons.so)
==38948==    by 0x4877522: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x114655: crear_conexion (sockets.c:163)
==38948==    by 0x10CF08: cliente_Memoria_Kernel (cliente.c:25)
==38948==    by 0x10D426: funcion_hilo_cliente_memoria (cliente.c:148)
==38948==  Block was alloc'd by thread #2
==38948== 
==38948== ----------------------------------------------------------------
==38948== 
==38948== Possible data race during write of size 1 at 0x4AAB1E7 by thread #2
==38948== Locks held: none
==38948==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38948==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38948==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==38948==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==38948==    by 0x48DE79E: printf (printf.c:33)
==38948==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==38948==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x114655: crear_conexion (sockets.c:163)
==38948==    by 0x10CF08: cliente_Memoria_Kernel (cliente.c:25)
==38948==    by 0x10D426: funcion_hilo_cliente_memoria (cliente.c:148)
==38948==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4912AC2: start_thread (pthread_create.c:442)
==38948==  Address 0x4aab1e7 is 55 bytes inside a block of size 1,024 alloc'd
==38948==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==38948==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==38948==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==38948==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==38948==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38948==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==38948==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==38948==    by 0x48DE79E: printf (printf.c:33)
==38948==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==38948==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x10D60C: hilos_kernel (cliente.c:202)
==38948==    by 0x10CBCA: main (main.c:28)
==38948==  Block was alloc'd by thread #1
==38948== 
==38948== ---Thread-Announcement------------------------------------------
==38948== 
==38948== Thread #3 was created
==38948==    at 0x49A39F3: clone (clone.S:76)
==38948==    by 0x49A48EE: __clone_internal (clone-internal.c:83)
==38948==    by 0x49126D8: create_thread (pthread_create.c:295)
==38948==    by 0x49131FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==38948==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x10D63A: hilos_kernel (cliente.c:205)
==38948==    by 0x10CBCA: main (main.c:28)
==38948== 
==38948== ----------------------------------------------------------------
==38948== 
==38948==  Lock at 0x11A380 was first observed
==38948==    at 0x4854BFE: pthread_mutex_init (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x10AE52: inicializar_mutex (funcionesAuxiliares.c:87)
==38948==    by 0x10CBB1: main (main.c:26)
==38948==  Address 0x11a380 is 0 bytes inside data symbol "mutex_log"
==38948== 
==38948== Possible data race during write of size 1 at 0x4AAB1B0 by thread #3
==38948== Locks held: none
==38948==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38948==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38948==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==38948==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==38948==    by 0x48DE79E: printf (printf.c:33)
==38948==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==38948==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x114655: crear_conexion (sockets.c:163)
==38948==    by 0x10D1AE: cliente_CPU_Kernel (cliente.c:89)
==38948==    by 0x10D4AE: funcion_hilo_cliente_cpu (cliente.c:163)
==38948==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4912AC2: start_thread (pthread_create.c:442)
==38948== 
==38948== This conflicts with a previous write of size 1 by thread #1
==38948== Locks held: 1, at address 0x11A380
==38948==    at 0x4859796: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38948==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38948==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==38948==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==38948==    by 0x48DE79E: printf (printf.c:33)
==38948==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==38948==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x10D6BC: hilos_kernel (cliente.c:216)
==38948==  Address 0x4aab1b0 is 0 bytes inside a block of size 1,024 alloc'd
==38948==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==38948==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==38948==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==38948==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==38948==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38948==    by 0x48F500B: outstring_func (vfprintf-internal.c:239)
==38948==    by 0x48F500B: __vfprintf_internal (vfprintf-internal.c:1517)
==38948==    by 0x48DE79E: printf (printf.c:33)
==38948==    by 0x4876800: txt_write_in_stdout (in /usr/lib/libcommons.so)
==38948==    by 0x4877570: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x10D60C: hilos_kernel (cliente.c:202)
==38948==    by 0x10CBCA: main (main.c:28)
==38948==  Block was alloc'd by thread #1
==38948== 
==38948== ---Thread-Announcement------------------------------------------
==38948== 
==38948== Thread #5 was created
==38948==    at 0x49A39F3: clone (clone.S:76)
==38948==    by 0x49A48EE: __clone_internal (clone-internal.c:83)
==38948==    by 0x49126D8: create_thread (pthread_create.c:295)
==38948==    by 0x49131FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==38948==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x10DACF: hilo_planificador_largo_plazo (planificacion.c:141)
==38948==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4912AC2: start_thread (pthread_create.c:442)
==38948==    by 0x49A3A03: clone (clone.S:100)
==38948== 
==38948== ---Thread-Announcement------------------------------------------
==38948== 
==38948== Thread #6 was created
==38948==    at 0x49A39F3: clone (clone.S:76)
==38948==    by 0x49A48EE: __clone_internal (clone-internal.c:83)
==38948==    by 0x49126D8: create_thread (pthread_create.c:295)
==38948==    by 0x49131FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==38948==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x10F2DF: planificador_corto_plazo (planificacion.c:692)
==38948==    by 0x11001D: iniciar_kernel (procesos.c:148)
==38948==    by 0x10CBE2: main (main.c:29)
==38948== 
==38948== ----------------------------------------------------------------
==38948== 
==38948==  Lock at 0x11A380 was first observed
==38948==    at 0x4854BFE: pthread_mutex_init (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x10AE52: inicializar_mutex (funcionesAuxiliares.c:87)
==38948==    by 0x10CBB1: main (main.c:26)
==38948==  Address 0x11a380 is 0 bytes inside data symbol "mutex_log"
==38948== 
==38948== Possible data race during write of size 1 at 0x4AAC250 by thread #5
==38948== Locks held: none
==38948==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38948==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38948==    by 0x48FDA9C: fputs (iofputs.c:38)
==38948==    by 0x48767C6: txt_write_in_file (in /usr/lib/libcommons.so)
==38948==    by 0x4877522: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x114655: crear_conexion (sockets.c:163)
==38948==    by 0x10CF08: cliente_Memoria_Kernel (cliente.c:25)
==38948==    by 0x110657: new_a_ready_procesos (procesos.c:309)
==38948==    by 0x10D8CB: funcion_new_ready_procesos (planificacion.c:65)
==38948==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4912AC2: start_thread (pthread_create.c:442)
==38948== 
==38948== This conflicts with a previous write of size 1 by thread #6
==38948== Locks held: 1, at address 0x11A380
==38948==    at 0x48597B4: mempcpy (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x4909664: _IO_new_file_xsputn (fileops.c:1235)
==38948==    by 0x4909664: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38948==    by 0x48FDA9C: fputs (iofputs.c:38)
==38948==    by 0x48767C6: txt_write_in_file (in /usr/lib/libcommons.so)
==38948==    by 0x4877522: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x10EFD0: hilo_planificador_corto_plazo (planificacion.c:613)
==38948==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==  Address 0x4aac250 is 0 bytes inside a block of size 4,096 alloc'd
==38948==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x48FCBA3: _IO_file_doallocate (filedoalloc.c:101)
==38948==    by 0x490BCDF: _IO_doallocbuf (genops.c:347)
==38948==    by 0x490AF5F: _IO_file_overflow@@GLIBC_2.2.5 (fileops.c:744)
==38948==    by 0x49096D4: _IO_new_file_xsputn (fileops.c:1243)
==38948==    by 0x49096D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==38948==    by 0x48FDA9C: fputs (iofputs.c:38)
==38948==    by 0x48767C6: txt_write_in_file (in /usr/lib/libcommons.so)
==38948==    by 0x4877522: _log_write_in_level (in /usr/lib/libcommons.so)
==38948==    by 0x48771D7: log_info (in /usr/lib/libcommons.so)
==38948==    by 0x114655: crear_conexion (sockets.c:163)
==38948==    by 0x10CF08: cliente_Memoria_Kernel (cliente.c:25)
==38948==    by 0x10D426: funcion_hilo_cliente_memoria (cliente.c:148)
==38948==  Block was alloc'd by thread #2
==38948== 
==38948== ----------------------------------------------------------------
==38948== 
==38948== Thread #1's call to pthread_mutex_lock failed
==38948==    with error code 22 (EINVAL: Invalid argument)
==38948==    at 0x4850D30: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x10CE13: liberar_espacio (main.c:99)
==38948==    by 0x10CC39: main (main.c:35)
==38948== 
==38948== ----------------------------------------------------------------
==38948== 
==38948== Thread #1 unlocked an invalid lock at 0x11A380
==38948==    at 0x48511E6: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x10CE49: liberar_espacio (main.c:102)
==38948==    by 0x10CC39: main (main.c:35)
==38948== 
==38948== ----------------------------------------------------------------
==38948== 
==38948== Thread #1's call to pthread_mutex_unlock failed
==38948==    with error code 22 (EINVAL: Invalid argument)
==38948==    at 0x4851311: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==38948==    by 0x10CE49: liberar_espacio (main.c:102)
==38948==    by 0x10CC39: main (main.c:35)
==38948== 
==38948== 
==38948== Use --history-level=approx or =none to gain increased speed, at
==38948== the cost of reduced accuracy of conflicting-access information
==38948== For lists of detected and suppressed errors, rerun with: -s
==38948== ERROR SUMMARY: 24711 errors from 11 contexts (suppressed: 689199 from 839)
